name: build-and-test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:

  # Build on all platforms
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '2.x', '3.x' ]
        exclude:
          # excludes python 2.x on Windows
          - os: windows-latest
            python-version: '2.x'

    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Build and install flydra_core
      run: python -m pip install ./flydra_core
    - name: Build and install flydra_analysis
      run: python -m pip install ./flydra_analysis

  # Test on Ubuntu only
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-latest]
        python-version: [ '2.x', '3.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Install system packages
      run: sudo apt install -y python-cairo python3-cairo
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Build and install flydra_core
      run: python -m pip install ./flydra_core
    - name: Test flydra_core
      run: |
        cd docs
        python -c "import nose; nose.run_exit()" --eval-attr="not (known_fail or slow_command)" --config ../flydra_core/setup.cfg
    - name: Build and install flydra_analysis
      run: python -m pip install ./flydra_analysis
    - name: Test flydra_analysis
      run: |
        cd docs
        python -c "import nose; nose.run_exit()" --eval-attr="not (known_fail or slow_command)" --config ../flydra_analysis/setup.cfg
